os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift package update
  - swift test
after_success: 
  - git clone https://github.com/dn-m/Documentarian && cd Documentarian
  - swift build -c release -Xswiftc -static-stdlib
  - cd ../
  - Documentarian/.build/Release/Documentarian
